name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy & Restart App on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            echo "ðŸ‘‰ Loading NVM"
            export NVM_DIR="/home/ubuntu/.nvm"
            source "$NVM_DIR/nvm.sh"
            source "$NVM_DIR/bash_completion"

            echo "ðŸ‘‰ Selecting Node version v22.18.0"
            export PATH="$PATH:/home/ubuntu/.nvm/versions/node/v22.18.0/bin"

            echo "ðŸ‘‰ Moving to project directory"
            cd ${{ secrets.PROJECT_PATH }}

            echo "ðŸ‘‰ Pulling latest code from GitHub"
            git pull origin main

            echo "ðŸ‘‰ Installing dependencies"
            npm install

            echo "ðŸ‘‰ Restarting PM2 service"
            pm2 restart kalasquareaws || pm2 start npm --name kalasquareaws -- run dev

            echo "âœ… Deployment completed successfully"s 

           